[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "cedarpy_conversor"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.optional-dependencies]
dev = [
    'maturin==1.1.0',
    'parameterized==0.9.0',
    'pip-tools==6.13.0',
    'pytest == 7.4.0',
]

[tool.maturin]
module-name = "cedarpy_conversor._internal"
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
log_cli = true
testpaths = [
    "tests/unit"
]